apiVersion: v1
kind: ConfigMap
metadata:
  name: alerts-adapter-config
  namespace: openshift-lightspeed
data:
  config.yaml: |
    pollInterval: 30s
    postRunDelay: 1h
    filtering:
      allowedReceivers:
        - critical
