{{- if .Values.openshiftLightspeed.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
{{ include "app-of-apps.metadata" (dict "name" .Values.openshiftLightspeed.name "namespace" .Values.argocd.namespace "syncWave" "2") }}
spec:
  ignoreDifferences:
    - group: ""
      kind: ConfigMap
      name: alerts-adapter-config
      jsonPointers:
        - /data
  destination:
    namespace: {{ .Values.openshiftLightspeed.namespace }}
    server: https://kubernetes.default.svc
  project: default
  source:
    path: openshift-lightspeed
    repoURL: {{ .Values.gitops.repoURL }}
    targetRevision: {{ .Values.gitops.targetRevision }}
    helm:
      valuesObject:
        subscription:
          source: {{ include "app-of-apps.operatorSource" . }}
        llm:
          apiUrl: {{ .Values.openshiftLightspeed.llm.apiUrl }}
          apiKey: {{ .Values.openshiftLightspeed.llm.apiKey }}
          provider: {{ .Values.openshiftLightspeed.llm.provider }}
          model: {{ .Values.openshiftLightspeed.llm.model }}
{{ include "app-of-apps.syncPolicy" . | indent 2 }}
{{- end }}
